DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Controllers/DashBoardController.cs
using DepoYonetimSistemi.DataAccessLayer;
using DepoYonetimSistemi.Web.Filters;
using DepoYonetimSistemi.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DepoYonetimSistemi.Web.Areas.Yonetim.Controllers
{
    [Kimlik, Yetki(Rol = EntityLayer.Enums.KullaniciYetkiler.Admin)]

    public class DashBoardController : Controller
    {
        public ActionResult Index()
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
                DashBoardModel model = new DashBoardModel()
                {
                    DepoAdet = uow.DepoRepository.GetCount(),
                    BugunHareketleri = uow.DepoHareketRepository.GetBugunkuHareketler(),
                    TopCikisAdet = uow.DepoHareketRepository.GetToplamCikisAdet(),
                    TopGirisAdet = uow.DepoHareketRepository.GetToplamGirisAdet(),
                };
                return View(model);
            }
        }
    }
}

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Controllers/DepoController.cs
using DepoYonetimSistemi.DataAccessLayer;
using DepoYonetimSistemi.EntityLayer;
using DepoYonetimSistemi.EntityLayer.Enums;
using DepoYonetimSistemi.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DepoYonetimSistemi.Web.Areas.Yonetim.Controllers
{
    [Kimlik,Yetki(Rol = KullaniciYetkiler.Admin)]
    public class DepoController : Controller
    {
        public ActionResult Index()
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.DepoRepository.GetAll());
        }

        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Insert(Depo model)
        {
            if (ModelState.IsValid)
            {
                using(UnitOfWork uow = new UnitOfWork())
                {
                    uow.DepoRepository.Add(model);
                    if (uow.SaveChanges() > 0) //Etkilenen Satır Sayısı 0 dan büyükse 
                        return RedirectToAction("Index");
                }
            }
            return View(model);

        }

        public ActionResult Update(int id = 0)
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
              var item = uow.DepoRepository.GetItem(id);
                if (item == null)
                    return RedirectToAction("Index");
                else
                    return View(item);
            }
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Update(Depo model)
        {
            if (ModelState.IsValid)
            {
                using(UnitOfWork uow = new UnitOfWork())
                {
                    uow.DepoRepository.Update(model);
                    if (uow.SaveChanges() > 0)
                        return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Delete(int id = 0)
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
               var item = uow.DepoRepository.GetItem(id);
               if(item == null)
                    return RedirectToAction("Index");
               else
                    return View(item);
            }
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Delete(Depo model)
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
              uow.DepoRepository.Delete(model.Id);
              uow.SaveChanges();
              return RedirectToAction("Index");
            }
        }
    }
}

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Controllers/KullaniciController.cs
using DepoYonetimSistemi.DataAccessLayer;
using DepoYonetimSistemi.EntityLayer;
using DepoYonetimSistemi.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DepoYonetimSistemi.Web.Areas.Yonetim.Controllers
{
    [Kimlik,Yetki(Rol = EntityLayer.Enums.KullaniciYetkiler.Admin)]
    public class KullaniciController : Controller
    {
        public ActionResult Index()
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.KullaniciRepository.GetAll());
        }

        public ActionResult Insert()
        {
            return View(new Kullanici());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Insert(Kullanici model)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.KullaniciRepository.Add(model);
                    if (uow.SaveChanges() > 0)
                        return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Update(int id = 0)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                var item = uow.KullaniciRepository.GetItem(id);
                if (item == null)
                    return RedirectToAction("Index");
                else
                    return View(item);
            }
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Update(Kullanici model)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.KullaniciRepository.Update(model);
                    if (uow.SaveChanges() > 0)
                        return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Delete(int id = 0)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                var item = uow.KullaniciRepository.GetItem(id);
                if (item == null)
                    return RedirectToAction("Index");
                else
                    return View(item);
            }
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Delete(Kullanici model)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                uow.KullaniciRepository.Delete(model.Id);
                uow.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Controllers/MalTurController.cs
using DepoYonetimSistemi.DataAccessLayer;
using DepoYonetimSistemi.EntityLayer;
using DepoYonetimSistemi.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DepoYonetimSistemi.Web.Areas.Yonetim.Controllers
{
    [Kimlik,Yetki(Rol = EntityLayer.Enums.KullaniciYetkiler.Admin)]
    public class MalTurController : Controller
    {
        public ActionResult Index()
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.MalTurRepository.GetAll());
        }

        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Insert(MalTur model)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.MalTurRepository.Add(model);
                    if (uow.SaveChanges() > 0)
                        return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Update(int id = 0)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                var item = uow.MalTurRepository.GetItem(id);
                if (item == null)
                    return RedirectToAction("Index");
                else
                    return View(item);
            }
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Update(MalTur model)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.MalTurRepository.Update(model);
                    if (uow.SaveChanges() > 0)
                        return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Delete(int id = 0)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                var item = uow.MalTurRepository.GetItem(id);
                if (item == null)
                    return RedirectToAction("Index");
                else
                    return View(item);
            }
        }


        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Delete(MalTur model)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                uow.MalTurRepository.Delete(model.Id);
                uow.SaveChanges();
                return RedirectToAction("Index");
            }
        }

    }
}

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Views/Shared/Hata.cshtml
@model System.Exception
@{
    ViewBag.Title = "Hata Sayfası";
}

<div class="row">
    <div class="col-12 text-center">
        <i class="fa fa-exclamation-triangle fa-3x text-warning"></i>
    </div>
</div>
<div class="row">
    <div class="col-12 text-center text-danger">
        Hata Oluştu!!
    </div>
</div>
<div class="row">
    <div class="col-12 text-center">
        @Model.Message
    </div>
</div>

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Views/Shared/YetkisizErisim.cshtml
@{
    ViewBag.Title = "YetkisizErisim";
}

<h2>Yetkisiz Erişim</h2>
<hr />
<h4>Yetkisiz Erişim Denemesi... Yöneticiniz ile iletişime geçiniz...</h4>

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Views/Shared/_Layout.cshtml
@using DepoYonetimSistemi.EntityLayer;
@using DepoYonetimSistemi.EntityLayer.Enums
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="@Url.Action("Index","DashBoard")">Depo Yönetim App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "DepoHareket")">Depo Hareketleri</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Depo")">Depolar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "MalTur")">Mal Türleri</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Kullanici")">Kullanıcılar</a>
                </li>
            </ul>
            <a class="btn btn-outline-warning" href="@Url.Action("Logout", "Login")">Çıkış</a>

        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>