DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Controllers/DepoHareketController.cs
using DepoYonetimSistemi.DataAccessLayer;
using DepoYonetimSistemi.EntityLayer;
using DepoYonetimSistemi.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DepoYonetimSistemi.Web.Areas.Yonetim.Controllers
{
    [Kimlik,Yetki(Rol = EntityLayer.Enums.KullaniciYetkiler.User)]
    public class DepoHareketController : Controller
    {
        public ActionResult Index(int depoId = 0)
        {
          using(UnitOfWork uow = new UnitOfWork())
            {
                List<Depo> depolar = new List<Depo>() { new Depo { Id = 0, Ad = "Hepsi" } };
                depolar.AddRange(uow.DepoRepository.GetAll());
                ViewBag.Depolar = new SelectList(depolar, "Id", "Ad", depoId);

                if (depoId == 0)
                    return View(uow.DepoHareketRepository.ToListFull());
                else
                    return View(uow.DepoHareketRepository.ToListFull(depoId));
            }
        }

        public ActionResult Insert()
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                ViewBag.Depolar = new SelectList(uow.DepoRepository.GetAll(), "Id", "Ad");
                ViewBag.MalTurleri = new SelectList(uow.MalTurRepository.GetAll(), "Id", "Ad");

                return View(new DepoHareket());
            }
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Insert(DepoHareket model)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.DepoHareketRepository.Add(model);
                    if (uow.SaveChanges() > 0)
                        return RedirectToAction("Index");
                }
            }

            using (UnitOfWork uow = new UnitOfWork())
            {
                ViewBag.Depolar = new SelectList(uow.DepoRepository.GetAll(), "Id", "Ad");
                ViewBag.MalTurleri = new SelectList(uow.MalTurRepository.GetAll(), "Id", "Ad");
                return View(new DepoHareket());
            }
        }
        public ActionResult Update(int id = 0)
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
               var item = uow.DepoHareketRepository.GetItem(id);
                if (item == null)
                    return RedirectToAction("Index");
                else
                {
                    ViewBag.Depolar = new SelectList(uow.DepoRepository.GetAll(), "Id", "Ad");
                    ViewBag.MalTurleri = new SelectList(uow.MalTurRepository.GetAll(), "Id", "Ad");
                    return View(item);
                }
            }
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Update(DepoHareket model)
        {
            if (ModelState.IsValid)
            {
                using(UnitOfWork uow = new UnitOfWork())
                {
                    uow.DepoHareketRepository.Update(model);
                    if (uow.SaveChanges() > 0)
                        return RedirectToAction("Index");
                }
            }

            using(UnitOfWork uow = new UnitOfWork())
            {
                ViewBag.Depolar = new SelectList(uow.DepoRepository.GetAll(), "Id", "Ad");
                ViewBag.MalTurleri = new SelectList(uow.MalTurRepository.GetAll(), "Id", "Ad");
                return View(model);
            }
        }

        public ActionResult Delete(int id = 0)
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
               var item = uow.DepoHareketRepository.GetItemFull(id);
               if (item == null)
                    return RedirectToAction("Index");
                else
                    return View(item);
            }
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Delete(DepoHareket model)
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
                uow.DepoHareketRepository.Delete(model.Id);
                uow.SaveChanges();
                return RedirectToAction("Index");
            }
        }

    }
}

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Views/DepoHareket/Delete.cshtml
@using DepoYonetimSistemi.EntityLayer
@model DepoHareket
@{
    ViewBag.Title = "Depo Hareket Sil";
}

<div class="row">
    <div class="col-12">
        <h3>Depo Hareketi Sil</h3>
    </div>
</div>
<hr />

@using (Html.BeginForm("Delete", "DepoHareket", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="row mb-2">
        <div class="col-12">
            <p><b>@Model.Depo.Ad</b> adlı depodaki <b>@Model.TarihSaat.ToShortDateString()</b> tarihli <b>@Model.Miktar.ToString("N2") @Model.Birim</b> miktarlı <b>@Model.MalTur.Ad</b> depo hareketini silmek istiyor musunuz?</p>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-sm-12">
            <a href="@Url.Action("Index", "DepoHareket")" class="btn btn-danger"><i class="fa fa-thumbs-down"></i> İptal</a>
            <button type="submit" class="btn btn-primary"><i class="fa fa-thumbs-up"></i> Kaydet</button>
        </div>
    </div>
}

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Views/DepoHareket/Index.cshtml
@using DepoYonetimSistemi.EntityLayer
@using DepoYonetimSistemi.EntityLayer.Enums

@model List<DepoHareket>
@{
    ViewBag.Title = "Depo Hareket Listesi";
}
<br />
<div class="row">
    <div class="col-12">
        <h3>Depo Hareket Listesi</h3>
    </div>
</div>
<hr />

@using (Html.BeginForm("Index", "DepoHareket", FormMethod.Get, new { @class = "row-mb-2" }))
{
    <div class="col-auto">
        <label for="depoId" class="col-form-label">Filtrele :</label>
    </div>
    <div class="col">
        <div class="input-group">
            @Html.DropDownList("depoId", ViewBag.Depolar as SelectList, new { @class = "form-select" })
            <button type="submit" class="btn btn-sm btn-outline-info"><i class="fa fa-refresh"></i></button>
        </div>
    </div>
}
<hr />
<div class="row">
    <div class="col-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Depo</th>
                    <th>Mal Türü</th>
                    <th>Hareket Tip</th>
                    <th>Tarih</th>
                    <th>Miktar</th>
                    <th>Açıklama</th>
                    <th>
                        <a href="@Url.Action("Insert", "DepoHareket")" class="btn btn-sm btn-primary">
                            <i class="fa fa-plus-circle"></i> Depo Hareket Ekle
                        </a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr>
                        <td colspan="8" class="align-middle text-center">
                            <span class="text-danger">Listelenecek depo hareketi bulunamadı...</span>
                        </td>
                    </tr>
                }
                else
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td class="align-middle">@item.Id</td>
                            <td class="align-middle">@item.Depo.Ad</td>
                            <td class="align-middle">@item.MalTur.Ad</td>
                            <td class="align-middle">
                                @if (item.HareketTipleri == DepoHareketTipleri.Giris)
                                {
                                    <span class="badge rounded-pill text-bg-info">Giriş</span>
                                }
                                else
                                {
                                    <span class="badge rounded-pill text-bg-warning">Çıkış</span>
                                }
                            </td>
                            <td class="align-middle">@item.TarihSaat.ToShortDateString()</td>
                            <td class="align-middle">@item.Miktar.ToString("N2") @item.Birim</td>
                            <td class="align-middle">@item.Aciklama</td>
                            <td class="align-middle">
                                <a href="@Url.Action("Delete", "DepoHareket", new { id = item.Id })" class="btn btn-sm btn-danger">
                                    <i class="fa fa-trash"></i> Sil
                                </a>
                                <a href="@Url.Action("Update", "DepoHareket", new { id = item.Id })" class="btn btn-sm btn-success">
                                    <i class="fa fa-pencil"></i> Düzenle
                                </a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Views/DepoHareket/Insert.cshtml
@using DepoYonetimSistemi.EntityLayer
@model DepoHareket
@{
    ViewBag.Title = "Depo Hareket Ekle";
}

<div class="row">
    <div class="col-12">
        <h3>Depo Hareketi Ekle</h3>
    </div>
</div>
<hr />
@using (Html.BeginForm("Insert", "DepoHareket", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="row mb-2">
        @Html.LabelFor(x => x.MalTurId, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.DropDownListFor(x => x.MalTurId, ViewBag.MalTurleri as SelectList, "Mal Türü Seçiniz...", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.MalTurId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.DepoId, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.DropDownListFor(x => x.DepoId, ViewBag.Depolar as SelectList, "Depo Seçiniz...", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.DepoId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.HareketTipleri, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EnumDropDownListFor(x => x.HareketTipleri, new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.HareketTipleri, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.TarihSaat, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.TarihSaat, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.TarihSaat, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Miktar, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Miktar, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Birim, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EnumDropDownListFor(x => x.Birim, new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.Birim, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Aciklama, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Aciklama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        <div class="offset-sm-2 col-sm-10">
            <a href="@Url.Action("Index", "DepoHareket")" class="btn btn-danger"><i class="fa fa-thumbs-down"></i> İptal</a>
            <button type="submit" class="btn btn-primary"><i class="fa fa-thumbs-up"></i> Kaydet</button>
        </div>
    </div>
}

DepoYonetimSistemi/DepoYonetimSistemi.Web/Areas/Yonetim/Views/DepoHareket/Update.cshtml
@using DepoYonetimSistemi.EntityLayer
@using DepoYonetimSistemi.EntityLayer.Enums
@model DepoHareket
@{
    ViewBag.Title = "Depo Hareketi Güncelle";
}

<div class="row">
    <div class="col-md-12">
        <h2>Depo Hareket Güncelle</h2>
    </div>
</div>
<hr />


@using (Html.BeginForm("Update", "DepoHareket", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="row mb-2">
        @Html.LabelFor(x => x.MalTurId, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.DropDownListFor(x => x.MalTurId, ViewBag.MalTurleri as SelectList, new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.MalTurId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.DepoId, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.DropDownListFor(x => x.DepoId, ViewBag.Depolar as SelectList, new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.DepoId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.HareketTipleri, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EnumDropDownListFor(x => x.HareketTipleri, new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.HareketTipleri, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.TarihSaat, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.TarihSaat, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.TarihSaat, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Miktar, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Miktar, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Birim, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EnumDropDownListFor(x => x.Birim, new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.Birim, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Aciklama, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Aciklama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-2">
        <div class="offset-sm-2 col-sm-10">
            <a href="@Url.Action("Index", "DepoHareket")" class="btn btn-danger"><i class="fa fa-thumbs-down"></i> İptal</a>
            <button type="submit" class="btn btn-primary"><i class="fa fa-thumbs-up"></i> Kaydet</button>
        </div>
    </div>
}